[package]
name = "iced_thawing"
version = "0.1.0"
edition = "2021"

[dependencies]
wasmtime = "29.0"
serde = { version = "1.0", features = ["derive", "rc"] }
bincode = "1.3"
tracing = "0.1"
tracing-subscriber = "0.3"
iced = { version = "0.14.0-dev", features = ["advanced", "debug"], git = "https://github.com/derezzedex/iced.git", rev = "f9e2118030c31f5de537bb173920e40149d6f75f" }
iced_core = { version = "0.14.0-dev", git = "https://github.com/derezzedex/iced.git", rev = "f9e2118030c31f5de537bb173920e40149d6f75f" }
notify-debouncer-mini = "0.6"