[package]
name = "thawing"
version = "0.1.0"
edition = "2021"

[dependencies]
wit-bindgen-rt = "0.41.0"
bincode = "1.0"
serde = "1.0"

[package.metadata.component]
package = "thawing:core"
target = { path = "../wit" }
bindings = { pub_export_macro = true }
