package thawing:core;

interface types {
  resource closure {
    constructor();

    id: func() -> u32;
  }

  resource element {}

  type bytes = list<u8>;
  
  record pixels {
    amount: f32,
  }

  record color {
    r: f32,
    g: f32,
    b: f32,
    a: f32
  }

  record padding {
    top: f32,
    right: f32,
    bottom: f32,
    left: f32,
  }

  variant length {
    fill,
    fill-portion(u16),
    shrink,
    fixed(f32),
  }

  enum horizontal {
    left,
    center,
    right,
  }
}

interface widget {
  use types.{element, closure, pixels, padding, length, horizontal, color};

  resource button {
    constructor(content: element);

    on-press-with: func(on-press: closure) -> button;
    into-element: func() -> element;
  }

  resource checkbox {
    constructor(label: string, is-checked: bool);

    on-toggle: func(on-toggle: closure) -> checkbox;
    into-element: func() -> element;
  }

  resource column {
    constructor();
    from-vec: static func(children: list<element>) -> column;

    spacing: func(amount: pixels) -> column;
    padding: func(padding: padding) -> column;
    width: func(width: length) -> column;
    height: func(height: length) -> column;
    max-width: func(width: pixels) -> column;
    align-x: func(align: horizontal) -> column;
    clip: func(clip: bool) -> column;

    push: func(child: element) -> column;
    extend: func(children: list<element>) -> column;

    into-element: func() -> element;
  }

  resource text {
    constructor(fragment: string);

    size: func(size: pixels) -> text;
    color: func(color: color) -> text;
    into-element: func() -> element;
  }
}

interface guest {
  use types.{element, closure, bytes};

  variant message {
    toggled(bool),
    increment,
    decrement,
  }
  
  resource table {
    constructor();
    call: func(c: closure) -> message;
    call-with: func(c: closure, state: bytes) -> message;
  }

  resource app {
    constructor(state: bytes);
    view: func() -> element;
  }
}

world thawing {
    import types;
    import widget;

    export guest;
}
