package component:iced-thawing;

interface types {
  resource element {}

  type pixels = f32;

  record color {
    r: f32,
    g: f32,
    b: f32,
    a: f32
  }
}

interface widget {
  use types.{element, pixels, color};
  use host.{message};

  resource button {
    constructor(content: element);

    on-press: func(message: message) -> button;
    into-element: func() -> element;
  }

  resource column {
    constructor();

    push: func(child: element) -> column;
    into-element: func() -> element;
  }

  resource text {
    constructor(fragment: string);

    size: func(size: pixels) -> text;
    color: func(color: color) -> text;
    into-element: func() -> element;
  }
}

interface host {
  variant message {
    increment,
    decrement,
  }
}

interface guest {
  use types.{element};

  resource app {
    constructor(value: s64);

    view: func() -> element;
  }
}

world thawing {
    import types;
    import widget;
    import host;

    export guest;
}
